### PR TITLE
[WIP, until I can test the changes]Update SocketRocket to square's master

### PR DESCRIPTION
**Pull request by taquitos**
We should consider this.

### CODE REVIEW

**Comment by JaviSoto** [comment]
:+1:

**Comment by corydolphin** [comment]
Are we using socket rocket anywhere? I believe we removed realtime from the
mac app a while ago.

**Comment by taquitos** [comment]
Actually, it looks like SocketIO needs it.

**Comment by corydolphin** [comment]
Mm.. Yes, it looks like CLSNotifier uses it still. I am sort of surprised. @mpirri do you know more about this?

**Comment by mpirri** [comment]
Notifier is currently unused - the backend does not function any more. Removing SocketRocket has been on our to-do list for some time. We need to move the notifier over to the faye system that (I believe) they are currently using.

**Pull request closed without merging**
